import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Faixa from "@/components/faixa";
import Image from "next/image";
import NavBar from "@/components/navBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Faixa type1={"Avon"} type2={"Natura"}/>
            <header className="flex flex-1/3 justify-between items-center px-5">
              <Image
                className="dark"
                src="/logo.svg"
                alt="Nilda Revende logomark"
                width={120}
                height={120}
              />
              <NavBar/>
              <div>Search</div>
            </header>
        {children}
      </body>
    </html>
  );
}
